export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";

export const FETCH_FAILED = "FETCH_FAILED";
export const UN_AUTHORISED = "UN_AUTHORISED";

export const SHOW_LOADER = "SHOW_LOADER";
export const CURRENT_ACTION = "CURRENT_ACTION";

export const LOGIN = "LOGIN";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const RESEND_EMAIL_CODE = "RESEND_EMAIL_CODE";
export const VERIFY_PASSWORD_CODE = "VERIFY_PASSWORD_CODE";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const REGISTER = "REGISTER";
export const VERIFY_EMAIL = "VERIFY_EMAIL";
export const TOKEN = "TOKEN";
export const USER = "USER";

export const EVENT_LISTING = "EVENT_LISTING";
export const CLAIM_EVENT = "CLAIM_EVENT";
export const CHECK_CLAIM_EVENT = "CHECK_CLAIM_EVENT";
export const FAVOURITE_EVENT_LISTING = "FAVOURITE_EVENT_LISTING";
export const ADD_FAVOURITE = "ADD_FAVOURITE";
export const EVENT_DETAIL = "EVENT_DETAIL";
export const EVENT_DETAIL_CLEAR = "EVENT_DETAIL_CLEAR";

export const COUNTRY_LIST = "COUNTRY_LIST";
export const CITY_LIST = "CITY_LIST";
export const EVENT_TYPE_LIST = "EVENT_TYPE_LIST";
export const DANCE_STYLE_LIST = "DANCE_STYLE_LIST";

export const GET_PROFILE = "GET_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const STRIPE_CONNECT = "STRIPE_CONNECT";
export const STRIPE_DISCONNECT = "STRIPE_DISCONNECT";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";

export const LOGOUT = "LOGOUT";
export const ADD_EVENT = "ADD_EVENT";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const VERIFY_EDIT_USER = "VERIFY_EDIT_USER";
export const CLEAR_EDIT_USER = "CLEAR_EDIT_USER";
export const CLEAR_EVENT = "CLEAR_EVENT";
export const ADD_ARTIST = "ADD_ARTIST";
export const CLEAR_ARTIST = "CLEAR_ARTIST";
export const DELETE_ARTIST = "DELETE_ARTIST";
export const CLEAR_DELETE_ARTIST = "CLEAR_DELETE_ARTIST";
export const ADD_TICKET = "ADD_TICKET";
export const CLEAR_TICKET = "CLEAR_TICKET";
export const DELETE_TICKET = "DELETE_TICKET";
export const CLEAR_DELETE_TICKET = "CLEAR_DELETE_TICKET";
export const ADD_SCHEDULE = "ADD_SCHEDULE";
export const CLEAR_SCHEDULE = "CLEAR_SCHEDULE";
export const DELETE_SCHEDULE = "DELETE_SCHEDULE";
export const TICKET_CHARGE = "TICKET_CHARGE";
export const TICKETS_CHARGE_COMPLETED = "TICKETS_CHARGE_COMPLETED";
export const PURCHASE_ONLINE_ACTIVE = "PURCHASE_ONLINE_ACTIVE";
export const CLEAR_DELETE_SCHEDULE = "CLEAR_DELETE_SCHEDULE";
